name: Build Vigil System

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Agent & Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    # Build the Agent
    - name: Build Agent (Linux)
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0
      run: |
        go mod tidy
        go build -o vigil-agent ./cmd/agent

    # Build the Server (for Docker/Hub)
    - name: Build Server (Linux)
      env:
        GOOS: linux
        GOARCH: amd64
        CGO_ENABLED: 0
      run: |
        go build -o vigil-server ./cmd/server

    # Upload BOTH files to the GitHub Action summary
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vigil-release
        path: |
          vigil-agent
          vigil-server